baseurl = 'http://replace.com/'
languageCode = 'en'
title = 'My New Hugo Site'
theme = "gohugo-theme-ananke"
themesDir = "../.."

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/paris_est_magique.jpg"
  recent_posts_number = 2
